library(Biobase)
library(lumi)
load("/home/ayates/brca/GSE31448/normed/SCAN.batch.8.RData")
load("/home/ayates/brca/GSE31448/normed/SCAN.batch.2.RData")
load("/home/ayates/brca/GSE31448/normed/SCAN.batch.5.RData")
load("/home/ayates/brca/GSE31448/normed/SCAN.batch.4.RData")
load("/home/ayates/brca/GSE31448/normed/SCAN.batch.3.RData")
load("/home/ayates/brca/GSE31448/normed/SCAN.batch.7.RData")
load("/home/ayates/brca/GSE31448/normed/SCAN.batch.1.RData")
load("/home/ayates/brca/GSE31448/normed/SCAN.batch.6.RData")
load("/home/ayates/brca/GSE31448/normed/UPC.batch.3.RData")
load("/home/ayates/brca/GSE31448/normed/UPC.batch.4.RData")
load("/home/ayates/brca/GSE31448/normed/UPC.batch.2.RData")
load("/home/ayates/brca/GSE31448/normed/UPC.batch.7.RData")
load("/home/ayates/brca/GSE31448/normed/UPC.batch.8.RData")
load("/home/ayates/brca/GSE31448/normed/UPC.batch.6.RData")
load("/home/ayates/brca/GSE31448/normed/UPC.batch.1.RData")
load("/home/ayates/brca/GSE31448/normed/UPC.batch.5.RData")
S.GSE31448 <- as.matrix(cbind(exprs(E.SCAN.batch.8), exprs(E.SCAN.batch.2), exprs(E.SCAN.batch.5), exprs(E.SCAN.batch.4), exprs(E.SCAN.batch.3), exprs(E.SCAN.batch.7), exprs(E.SCAN.batch.1), exprs(E.SCAN.batch.6)))
U.GSE31448 <- as.matrix(cbind(exprs(E.UPC.batch.3), exprs(E.UPC.batch.4), exprs(E.UPC.batch.2), exprs(E.UPC.batch.7), exprs(E.UPC.batch.8), exprs(E.UPC.batch.6), exprs(E.UPC.batch.1), exprs(E.UPC.batch.5)))
# convert to Biobase
# plot hist, boxplot, density
save(S.GSE31448, U.GSE31448, file="/home/ayates/brca/GSE31448/normed/GSE31448.SCANUPC.RData")
E.S.GSE31448 <- ExpressionSet(S.GSE31448)
E.U.GSE31448 <- ExpressionSet(U.GSE31448)
sample.median.scan <- apply(S.GSE31448, 2, median)
sample.median.upc <- apply(U.GSE31448, 2, median)
feature.median.scan <- apply(S.GSE31448, 1, median)
feature.median.upc <- apply(U.GSE31448, 1, median)
sample.mean.scan <- apply(S.GSE31448, 2, mean)
sample.mean.upc <- apply(U.GSE31448, 2, mean)
feature.mean.scan <- apply(S.GSE31448, 1, mean)
feature.mean.upc <- apply(U.GSE31448, 1, mean)

pdf('~/density.pdf', height=12, width=12)
density(E.S.GSE31448, addLegend=F, main="SCAN density")
density(E.U.GSE31448, addLegend=F, main="UPC density")
dev.off()
pdf("~/boxplots.pdf", height=8, width=60)
boxplot(E.S.GSE31448, main="SCAN")
boxplot(E.U.GSE31448, main="UPC")
dev.off()
pdf("~/hists.pdf")
hist(sample.median.scan, main="Sample Median SCAN")
hist(sample.median.upc, main="Sample Median UPC")
hist(feature.median.scan, main="Feature Median SCAN")
hist(feature.median.upc, main="Feature Median UPC")
hist(sample.mean.scan, main="Sample Mean SCAN")
hist(sample.mean.upc, main="Sample Mean UPC")
hist(feature.mean.scan, main="Feature Mean SCAN")
hist(feature.mean.upc, main="Feature Mean UPC")
dev.off()

write.table(S.GSE31448, file="~/GSE31448.SCAN.tab", col.names=NA, row.names=T, sep="\t")
write.table(U.GSE31448, file="~/GSE31448.UPC.tab", col.names=NA, row.names=T, sep="\t")
